.github/workflows/tests.yml
Dockerfile
Makefile
README.md

Introduce a Dockerfile that will be built/pushed to AWS ECR to be consumed by AWS App Runner later.

:technologist: Dockerfile and build targets

---

.dockerignore
Makefile
README.md
src/main/settings.py
terraform/apprunner.tf
terraform/ecr.tf
terraform/iam-policies.tf
terraform/main.tf
terraform/outputs.tf
terraform/ssm.tf
terraform/terraform.tfvars
terraform/variables.tf

Currently deployed under:
https://qechprqjst.eu-central-1.awsapprunner.com/
Next up:
- fix assets (CSS, images, JS)
- setup PostgreSQL
- custom domain setup
- setup CI

:sparkles: Deploy to AWS App Runner, fixes #80

---

requirements.txt

```
make -B requirements.txt
```

:arrow_up: Bump requirements

---

Dockerfile

We now run the `collectstatic` as part of the Docker image build

:bug: fix assets (CSS, images, JS)

---

.github/workflows/deployment.yml
.github/workflows/tests.yml
Makefile
README.md

Build the Docker image, push it to the registry and Terraform apply

:construction_worker: Continuous Delivery

---

Dockerfile
Makefile
src/main/settings.py
terraform/apprunner.tf
terraform/variables.tf

Also adjust Dockerfile multistage build so the base image is binary compatible with the final one (needed for PostgreSQL shared libraries).

:sparkles: Allow CORS for Netlify preview

---

src/main/settings.py
terraform/apprunner.tf
terraform/variables.tf

This should fix the CSRF error on /admin/
Also fix `PRODUCTION` environment variable decoding

:wrench: Configurable CSRF_TRUSTED_ORIGINS

---

requirements.txt
setup.cfg
src/main/settings.py
src/main/tests.py
src/main/urls.py
terraform/apprunner.tf
terraform/ssm.tf
terraform/variables.tf

Only introduce the reset password feature for now. Configure the SMTP server to send emails.

:sparkles: Setup djoser for password reset, fixes #98

---

.github/workflows/deployment.yml
Makefile

Check and apply migrations as part of the deployment. The `migrations` job would fail if we're missing migrations.
Fixes #33 and fixes #54

:construction_worker: Automate DB migration deployment

---

.github/workflows/deployment.yml
terraform/variables.tf

Update AWS deployment automation user & role.
This is related to mynotif-infra update, refs:
https://github.com/mynotif/mynotif-infra/pull/1

:construction_worker: Update AWS deployment automation

---

src/nurse/tests/test_views.py

Introduces pytest fixtures as it provides more flexibility than setup/teardown

:recycle: Use pytest fixtures to setup/teardown

---

src/nurse/models.py
src/nurse/tests/test_models.py

The function returns a queryset containing the Prescription objects.

:sparkles: Add function to fetch expiring prescriptions

---

src/nurse/management/commands/_notifications.py
src/tests/nurse/management/commands/test_notifications.py

The OneSignal notification payload couldn't be serialized because of the Set object.
While the fix was easy, the test required deeper mocking. The error was:
```
Object of type set is not JSON serializable.
```

:bug: Fix notification serialization error

---

.github/workflows/deployment.yml

Force AppRunner redeployment on merge to main

:construction_worker: Force AppRunner redeployment

---

terraform/lambda.tf

From the default 3 seconds to 10 seconds

:wrench: Bump notification lambda timeout

---

Makefile

As we migrated the AppRunner region, the ARN changed, refs #161

:wrench: Adjust AppRunner ARN

---

Makefile
setup.cfg

Later we can hook this up with a service to track the coverage history

:construction_worker: Introduce test coverage

---

src/nurse/views.py
src/tests/nurse/test_views.py

- add missing `__init__.py` file
- fix `EMAIL_HOST_USER` usage to come from settings

:white_check_mark: Fix broken email test

---

src/tests/nurse/test_views.py

The tests were actually updating the first_name and last_name fields

:white_check_mark: Clarify the user update tests

---

src/tests/nurse/test_views.py

Also assert full response.data on status code != 200

:white_check_mark: Assert response.data
