- src/main/settings.py
- terraform/apprunner.tf
- terraform/ssm.tf
- terraform/variables.tf
Note that the database isn't currently terraformed as we're consuming the free tier from Supabase. Later we will consume our own AWS RDS.
> :sparkles: Connect to PostgreSQL

- Dockerfile
Reduce from 378MB to 223MB using multistage builds. This doesn't have an impact on application performance, only on deployment speed
> :zap: Improve Docker image size

- src/main/settings.py
The warnings were:
```
venv/lib/python3.11/site-packages/django/conf/__init__.py:267
/home/andre/workspace/mynotif-backend/venv/lib/python3.11/site-packages/django/conf/__init__.py:267: RemovedInDjango50Warning: The USE_L10N setting is deprecated. Starting with Django 5.0, localized formatting of data will always be enabled. For example Django will display numbers and dates using the format of the current locale.
warnings.warn(USE_L10N_DEPRECATED_MSG, RemovedInDjango50Warning)
venv/lib/python3.11/site-packages/django/conf/__init__.py:274
/home/andre/workspace/mynotif-backend/venv/lib/python3.11/site-packages/django/conf/__init__.py:274: RemovedInDjango51Warning: The DEFAULT_FILE_STORAGE setting is deprecated. Use STORAGES instead.
warnings.warn(DEFAULT_FILE_STORAGE_DEPRECATED_MSG, …
```
> :rotating_light: Fix depreciation warnings

- src/nurse/serializers.py
- src/nurse/tests.py
This commit removes the prescription limit in the PatientSerializer's get_prescriptions method. Previously, the method was fetching only the two most recent prescriptions related to the patient. Now, it retrieves all prescriptions associated with the patient, allowing for a comprehensive list of prescriptions.
Changes made:
- Removed the [:2] from the Prescription.objects.filter query in get_prescriptions method.
This modification ensures that all prescriptions related to the patient will be included in the serialized output,
providing a complete record of the patient's prescriptions in the API response.
> :wrench: Remove prescription limit in PatientSerializer

- src/nurse/tests/test_views.py
- src/nurse/urls.py
- src/nurse/views.py
Introduce a new endpoint `/notify/` to send notifications.
The endpoint is under authentication and only staff users are allowed
> :sparkles: Admin notification view

- .github/workflows/deployment.yml
- .github/workflows/tests.yml
- src/main/settings.py
- src/main/urls.py
- src/nurse/tests/test_views.py
- terraform/backend.tf
API changed between moto 4 and moto 5. The error was:
```
ImportError while importing test module 'mynotif-backend/src/nurse/tests/test_views.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
src/nurse/tests/test_views.py:13: in <module>
from moto import mock_s3
E   ImportError: cannot import name 'mock_s3' from 'moto' (mynotif-backend/venv/lib/python3.11/site-packages/moto/__init__.py)
```
Also bumped GitHub Actions versions.
Also update formatting after black got updated and the Terraform code, the error was:
```
│ Error: Cannot assume IAM Role
│
│ IAM Role ARN not set
│   on backend.tf line 4, in terraform:
│    4:   backend "s3" …
```
> :white_check_mark: Update broken unit tests

- .env.example
- Makefile
- src/main/settings.py
- terraform/apprunner.tf
- terraform/backend.tf
- terraform/main.tf
- terraform/ssm.tf
Also update Terraform backend provider version to fix deprecated role_arn field, refs:
https://github.com/cloudposse/terraform-aws-tfstate-backend/issues/146
Also update the `devops/aws/redeploy/apprunner` make target to specify the region and change redeployment command, the errors were:
```
The service arn provided in the request does not belong to the current region
No configurations provided in the UpdateService request.
```
> :lock: Migrate secret key to SSM, fix #63

- terraform/apprunner.tf
- terraform/route53.tf
- terraform/variables.tf
New domain: ordopro.fr
Also apply fixes related to terraform-aws-tfstate-backend, the errors were:
```
Warning: Deprecated Parameters
on backend.tf line 4, in terraform:
4:   backend "s3" {
The following parameters have been deprecated. Replace them as follows:
* role_arn -> assume_role.role_arn
Error: Cannot assume IAM Role
IAM Role ARN not set
```
> :wrench: Frontend domain Vercel

- src/nurse/templates/emails/email_template.html
- src/nurse/views.py
- src/tests/nurse/test_views.py
1. Modify the `SendEmailToDoctorView` to use the user's email address as the `from_email` parameter in the `send_mail` function, instead of the `EMAIL_HOST_USER` environment variable. This ensures that the email is sent from the user's email address, allowing the recipient to reply directly to the user.
2. Remove the sentence "Cet e-mail a été envoyé à partir d'une adresse e-mail dédiée au renouvellement et n'accepte pas de réponses." from the email template.
This message is no longer necessary
since the email is now sent from the user's email address.
3. Update the test `test_send_email_to_doctor` to verify that the email is sent from the user's email address and
that the "no-reply" message is no longer present in the email body.
To see for more information …
> :bug: remove no-reply notice and update sender email fix #165

- requirements.txt
- setup.cfg
Also bump to Cython 3, the build error was fixed in later version, refs https://github.com/mynotif/mynotif-backend/pull/115
Note that Django 5.1 is breaking djoser 2.2.3, the error is:
```
_pickle.PicklingError: Cannot pickle ResolverMatch
```
Refs https://github.com/sunscrapers/djoser/issues/842
> :arrow_up: Bump to Django 5

- .github/workflows/deployment.yml
- terraform/lambda.tf
- terraform/main.tf
- terraform/variables.tf
This is a follow up for #172, but 3.13 isn't yet available in lambdas
Split this PR up as it's doing backend optimizations as well.
> :arrow_up: Bump AWS Lambda Python runtime to 3.12

- src/nurse/serializers.py
- src/nurse/views.py
- src/tests/nurse/test_views.py
Let the frontend choose the field subset dynamically on /patient/ using the `field` query parameter. Returns all fields by default.
Example:
GET /patient/?fields=id,firstname,lastname
This should improve the performance on the GET /patient/ endpoint.
> :zap: Dynamic patient fields selection

- src/nurse/serializers.py
- src/nurse/views.py
- src/tests/nurse/test_views.py
Added patient_firstname and patient_lastname fields to the PrescriptionSerializer to include patient name details in prescription responses.
Updated test cases to validate these new fields.
These changes address multiple requests
for expanded patient information in prescription data.
> Add patient first and last names to prescription serializer

- src/main/serializers.py
- src/main/urls.py
- src/main/views.py
- src/nurse/serializers.py
- src/nurse/views.py
- src/tests/main/test_core.py
- src/tests/nurse/test_views.py
Introduce `/api/v2/account/register` for account creation using email and `/api/v2/api-token-auth/` for authentication using email. Note that we tried to take a different approach for addressing email authentication. Instead of using a custom `AUTH_USER_MODEL` we still use the same default model, but feed the `username` with the `email` during register and login phases.
Note that while we didn't write any User.email -> User.username data migration script, it's possible to deal with it later if we want to. This assumes existing user can still login using their username rather than email.
> :sparkles: Email authentication, fixes #168

- src/main/urls.py
Copy the existing routes to `/api/v1/` but still keep them until the frontend migrate them.
> :sparkles: Versioned API design, fixes #183

- src/nurse/views.py
- src/tests/nurse/test_views.py
The `/api/v1/user/` endpoint to return only the logged in user.
> :lock: Prevent from listing all users

- terraform/route53.tf
Setup instructions:
- https://mailadmin.zoho.eu/cpanel/home.do#domains/ordopro.fr/emailConfig/mx
- https://mailadmin.zoho.eu/cpanel/home.do#domains/ordopro.fr/emailConfig/spf
- https://mailadmin.zoho.eu/cpanel/home.do#domains/ordopro.fr/emailConfig/dkim/dkim-listing
New EMAIL_HOST, EMAIL_HOST_USER and EMAIL_HOST_PASSWORD credentials configured in AWS Systems Manager > Parameter Store.
> :bricks: Zoho Mail Exchanger (MX) Records, fixes #176

- terraform/route53.tf
- terraform/variables.tf
Update the domain mapping.
- ordopro.fr APEX root to map to the marketing landing page
- app.ordopro.fr to map to the React App hosted via Vercel
The marketing landing page is behind GitHub Action static pages, see: https://github.com/mynotif/website
Also see https://github.com/mynotif/website/pull/1
> :bricks: Frontend app subdomain

- terraform/s3.tf
This bucket is used to store prescription file uploads. The bucket already exited as it was created manually, but it's now mapped with Terraform, fixes #62
> :bricks: Terraform the prescription s3 bucket

- src/nurse/admin.py
- src/nurse/views.py
- src/tests/nurse/test_views.py
This update adds administration classes for Subscription and StripeProduct templates to the `nurse/admin.py` file.
Changes include:
1. Addition of the `StripeProductAdmin` class to manage the display and editing of Stripe products in the admin.
2. Addition of the `SubscriptionAdmin` class to manage the display and editing of subscriptions in the admin.
3. Updated `views.py` file to use Stripe API key from configuration parameters.
4. Added a new `checkout_url` field in the subscription creation response to return the Stripe checkout URL.
5. Updated unit tests to check the new response with the checkout URL.
> :sparkles: Add admin for Subscription and StripeProduct

- src/tests/conftest.py
- src/tests/nurse/test_views.py
- Moved shared test fixtures (`user`, `staff_user`, `authenticated_client`, etc.) to a dedicated `conftest.py` file.
- Removed duplicate definitions of these fixtures from `test_views.py`.
- Ensured consistent import and reuse of fixtures and utility functions across tests.
> :recycle: Centralize and reuse test fixtures with conftest.py

- src/payment/urls.py
- src/payment/views.py
- src/tests/payment/test_views.py
- Added endpoint for user subscription cancellation (`SubscriptionUserCancelView`).
- Update routes to include the new user subscription cancellation endpoint.
- Created a test to verify that user subscription cancellation works.
- Simulated Stripe behavior with a mock in tests to avoid real API calls.
> :sparkles: Add to cancel a subscription

- src/main/urls.py
- src/main/views.py
- src/tests/main/test_views.py
Custom exception handlers for 400 and 500.
Leverage the custom exception handlers from Django Rest Framework to always return a JSON response.
Not that 404 exceptions should also return a JSON response as long as we implement the DRF `APIView`.
Alternatively we could have used the `REST_FRAMEWORK.EXCEPTION_HANDLER`, but using the implementation provided by Django Rest Framework for both `handler500` and `handler400` seemed more straightforward.
Find out more:
https://www.django-rest-framework.org/api-guide/exceptions/
> :goal_net: Custom exception handlers

- .github/workflows/tests.yml
This is needed for the Terraform linting via `terraform fmt`. The error was:
```
terraform -chdir=terraform fmt -recursive -diff -check
make: terraform: No such file or directory
```
See: https://github.com/mynotif/mynotif-backend/actions/runs/12894486549/job/35953235371?pr=215
> :construction_worker: Make sure Terraform is available

- .env.example
- src/main/settings.py
- src/payment/urls.py
- src/payment/views.py
- src/tests/payment/test_views.py
- Add FRONTEND_URL environment variable with localhost default
- Replace backend success/cancel endpoints with frontend URLs
- Remove unused SubscriptionSuccessView and SubscriptionCancelView
- Update related tests
- Add FRONTEND_URL to .env.example
> :sparkles: add FRONTEND_URL env var for dynamic Stripe redirection URLs

- terraform/apprunner.tf
- terraform/ssm.tf
- terraform/variables.tf
- Added Stripe environment variables (STRIPE_API_KEY, STRIPE_WEBHOOK_SECRET) to the AppRunner service configuration.
- Added frontend_url variable to support Stripe redirects.
- Created SSM parameter data sources for Stripe API key and webhook secret.
> :sparkles: Add Stripe and frontend URL configuration to AppRunner
